name: Build and Package

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like v1.0.0
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: windows-latest  # Windows required for x86/x64 builds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up xmake
        run: |
          Invoke-WebRequest -Uri https://xmake.io/shget.text -OutFile install.ps1
          powershell -File install.ps1
          echo "$HOME/.xmake/bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Build with xmake
        run: |
          xmake f -p windows -a x86 -m release
          xmake -v

      - name: Package the executable and DLL
        run: |
          xmake package
          mkdir dist
          cp ./packaged/* dist/

      - name: Create ZIP archive
        run: |
          $version = xmake lua -v "print(_G.project_version())"
          Compress-Archive -Path ./dist/* -DestinationPath "MouseSim-v$version.zip"

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: MouseSim-Package
          path: MouseSim-v*.zip

      # Optional: Upload to GitHub Releases (only if triggered by a tag)
      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: MouseSim-v*.zip