name: Build and Package

permissions:
  contents: write
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # Windows required for x86/x64 builds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set xmake env
        run: echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/xmake-global" >> $GITHUB_ENV
        shell: bash

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev
          actions-cache-folder: .xmake-cache-W${{ steps.cache_key.outputs.key }}

      - name: Build with xmake
        run: |
          xmake f -p windows -a x86 -m release
          xmake -v

      - name: Package the executable and DLL
        run: |
          xmake package
          mkdir dist
          cp ./packaged/* dist/

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MouseSim-x86
          path: |
            packaged
