name: Build and Package

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like v1.0.0
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: windows-latest  # Windows required for x86/x64 builds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set xmake env
        run: echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/xmake-global" >> $GITHUB_ENV
        shell: bash

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev
          actions-cache-folder: .xmake-cache-W${{ steps.cache_key.outputs.key }}

      - name: Build with xmake
        run: |
          xmake f -p windows -a x86 -m release
          xmake -v

      - name: Package the executable and DLL
        run: |
          xmake package
          mkdir dist
          cp ./packaged/* dist/

      - name: Create ZIP archive
        run: |
          $version = xmake lua "print(_G.project_version() or '1.0.0')"
          if (-not $version -or $version -match 'error') { $version = "1.0.0" }
          $zipName = "MouseSim-v$version.zip"
          Compress-Archive -Path "./dist/*" -DestinationPath "$zipName" -Force
          if (-not (Test-Path -Path "$zipName")) { exit 1 }

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: MouseSim-Package
          path: MouseSim-v*.zip

      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: MouseSim-v*.zip
